-- Collab Deal OS V1 Supabase/Postgres schema starter.
create table if not exists public.users (
  id uuid primary key,
  account_type text not null check (account_type in ('creator','brand','admin')),
  plan text not null default 'free' check (plan in ('free','pro','premium')),
  evaluation_count integer not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.creator_profiles (
  user_id uuid primary key references public.users(id) on delete cascade,
  display_name text not null,
  instagram_url text not null,
  niche text,
  location text,
  average_views bigint default 0,
  engagement_rate numeric default 0,
  metric_status text not null default 'creator-declared' check (metric_status in ('creator-declared','verified','unavailable'))
);
create table if not exists public.brand_profiles (
  user_id uuid primary key references public.users(id) on delete cascade,
  brand_name text not null,
  website text,
  category text,
  logo_url text
);
create table if not exists public.social_accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  platform text not null,
  profile_url text,
  followers bigint default 0,
  subscribers bigint default 0,
  metric_status text not null default 'creator-declared'
);
create table if not exists public.campaigns (
  id uuid primary key default gen_random_uuid(),
  brand_user_id uuid not null references public.users(id) on delete cascade,
  name text not null,
  budget numeric not null check (budget >= 0),
  objective text,
  target_niche text,
  target_location text,
  platform text,
  deliverables jsonb not null default '[]'::jsonb,
  product_value numeric not null default 0,
  usage_rights text,
  exclusivity text,
  timeline text,
  status text not null default 'draft',
  created_at timestamptz not null default now()
);
create table if not exists public.offers (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  creator_user_id uuid not null references public.users(id) on delete cascade,
  payment numeric not null check (payment >= 0),
  product_value numeric not null default 0,
  status text not null default 'sent' check (status in ('sent','accepted','rejected','revised','expired')),
  created_at timestamptz not null default now()
);
create table if not exists public.offer_revisions (
  id bigint generated by default as identity primary key,
  offer_id uuid not null references public.offers(id) on delete cascade,
  revised_by uuid not null references public.users(id),
  payment numeric,
  product_value numeric,
  terms jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.deal_analyses (
  id uuid primary key default gen_random_uuid(),
  offer_id uuid references public.offers(id) on delete cascade,
  requested_by uuid not null references public.users(id),
  fair_low numeric not null,
  fair_high numeric not null,
  deal_score integer not null,
  confidence integer not null,
  counter_offer numeric,
  explanation text,
  created_at timestamptz not null default now()
);
create table if not exists public.subscriptions (
  user_id uuid primary key references public.users(id) on delete cascade,
  provider text not null default 'razorpay',
  provider_subscription_id text,
  plan text not null,
  status text not null,
  updated_at timestamptz not null default now()
);
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  type text not null,
  body text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create or replace view public.opportunities_view as select * from public.campaigns where status in ('active','published');
-- Enable RLS before production and add creator/brand policies appropriate to your auth.uid() model.
